# TrackRecord PostgreSQL template database configuration. Syntax taken from
# "http://blog.bleything.net/" (Ben Bleything, June 2006).

dbinfo: &dbinfo
  adapter: postgresql
  host: /path/to/database/
  username: username-goes-here
  password: password-goes-here

development:
  <<: *dbinfo
  database: trackrecord-devel

production:
  <<: *dbinfo
  database: trackrecord

# Warning: The database defined as 'test' will be erased and re-generated
# from your development database when you run 'rake'. Do not set this to
# the same as development or production.

test:
  <<: *dbinfo
  database: trackrecord-test
